### ISSUE TITLE
Install rJava on VM as a dependency for Expands

### ISSUE THREAD

**Issue by BrunoGrandePhD** [morinlab/galaxy_tools#9]

**Comment by sjessa** [comment]
Installed rJava on nova with `sudo apt-get install r-cran-rjava`; adding `package_r_3_1_2_rjava1` which configures rJava with the right paths etc, along with the EXPANDS wrapper
For future reference, these helped:
- [rJava on Ubuntu](http://stackoverflow.com/questions/23469061/why-does-rjava-not-work-on-ubuntu-14-04-using-openjdk-7)
- [paths re: rjava](http://stackoverflow.com/questions/3311940/r-rjava-package-install-failing/3311983#3311983)  
- [permissions re: rJava](http://stackoverflow.com/questions/25232624/r-package-rjava-only-loads-if-i-launch-r-with-sudo)
